version: '3'
services:
  devbox:
    container_name: dev-keystone
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
        - .:/home/node/app
        - node_modules:/home/node/app/node_modules
    environment:
        - DATABASE_URL=postgres://postgres:password@postgres:5432/todo
        - WAIT_HOSTS=postgres:5432
    ports:
    - "3000:3000"
    # command: sh -c './wait-for-postgres.sh && yarn dev'
    # command: ["yarn", "dev"]
    command: sh -c '.wait-for && yarn dev'
    # links:
    #     - postgres
    depends_on:
        - postgres
    # command: sh -c './wait-for postgres:5432 -- yarn dev'
  # production-server:
  #   container_name: service-name
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #       - .:/app
  #   environment:
  #       - DATABASE_URL=postgres://user:password@postgres:5432/database-name
  #   ports:
  #   - "3000:3000"
  #   command: ["./dumb-init", "yarn", "start"]
  #   links:
  #       - postgres
  postgres:
    image: "postgres:12"
    container_name: "postgres"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=todo
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
  node_modules: